image: node:17.5.0
pipelines:
  branches:
    master:
       - step:
            name: A REAL build process!
            caches:
              - node
            script:
              - npm install
              - npm run build
              - sudo apt-get install zip unzip
              - zip -r sample_build.zip sample_build
            artifacts:
              - build/**
              - sample_build.zip
       - step:
          name: Deploy sample_build.zip to server via SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/var/www/deployedstuff/build'
                LOCAL_PATH: 'node_modules.tar.gz'
      