pipelines:
  branches:
    master:
       - step:
            name: Compress the package into a Martini-compatible ZIP file
            script:
              - cd packages
              - sudo apt-get -y install zip unzip
              - zip -qr ../baluyut-bamboopackage.zip baluyut_bamboopackage/
            artifacts:
              - packages/baluyut-bamboopackage.zip
       - step:
            name: ZIP package deployment to Remote Martini Instance Server
            script:
              - sudo apt-get -y install jq
              - pampalub=$(curl -X POST $TOKENURL -H 'Accept:application/json' -H 'Content-Type:application/x-www-form-urlencoded' -d "grant_type=password&username="$TOROUSR"&password="$TOROPSW"&client_id=TOROMartini&client_secret=TOROMartini" | jq -r .access_token)
              - curl -X POST "$TOROURL/esbapi/packages/upload?stateOnCreate=STARTED&replaceExisting=true" -H  "accept:application/json" -H  "Content-Type:multipart/form-data" -F "file=@baluyut-bamboopackage.zip;type=application/x-zip-compressed" -H "Authorization:Bearer $pampalub"