pipelines:
  branches:
    master:
       - step:
            name: Zipping         
            script:
              - cd packages
              - sudo apt-get install zip unzip
              - zip -r baluyut-samplepackage.zip baluyut-samplepackage/
            artifacts:
              - packages/baluyut-samplepackage.zip
       - step:
            name: Deployment
            script:
              - pasoksusi=$(curl -X POST https://toro282.us-east.toroserver.com/oauth/token -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=password&username=toro.ricardomiguel.baluyut@gmail.com&password=Ad0lfONG_m4lupet&client_id=TOROMartini&client_secret=TOROMartini' | jq -r .access_token)
			  - curl -X POST "https://toro282.us-east.toroserver.com/esbapi/packages/upload?stateOnCreate=STARTING" -H "accept: application/json" -H  "Content-Type: multipart/form-data" -H "Authorization: Basic dG9yby5yaWNhcmRvbWlndWVsLmJhbHV5dXRAZ21haWwuY29tOitZfXc4PVcuQDZ0Sik=" -F "entryList=List []" Bearer pasoksusi
			  
              
              